//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.25 at 06:17:47 PM IST 
//


package edu.wustl.common.cde.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XMLCDECacheType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLCDECacheType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="XMLCDE" type="{}XMLCDE" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="refreshTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="lazyLoading" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLCDECacheType", propOrder = {
    "xmlcde"
})
public class XMLCDECacheType {

    @XmlElement(name = "XMLCDE", required = true)
    protected List<XMLCDE> xmlcde;
    @XmlAttribute
    protected Integer refreshTime;
    @XmlAttribute
    protected Boolean lazyLoading;

    /**
     * Gets the value of the xmlcde property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xmlcde property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXMLCDE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLCDE }
     * 
     * 
     */
    public List<XMLCDE> getXMLCDE() {
        if (xmlcde == null) {
            xmlcde = new ArrayList<XMLCDE>();
        }
        return this.xmlcde;
    }

    /**
     * Gets the value of the refreshTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRefreshTime() {
        return refreshTime;
    }

    /**
     * Sets the value of the refreshTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRefreshTime(Integer value) {
        this.refreshTime = value;
    }

    /**
     * Gets the value of the lazyLoading property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLazyLoading() {
        return lazyLoading;
    }

    /**
     * Sets the value of the lazyLoading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLazyLoading(Boolean value) {
        this.lazyLoading = value;
    }

}
