
package edu.wustl.common.querysuite.queryobject;

/**
 * An immutable wrapper around int used to uniquely identify an expression
 * within a query. It is autogenerated when an expression is added to a query.
 * @see edu.wustl.common.querysuite.queryobject.IConstraints#addExpression(IFunctionalClass)
 * @version 1.0
 * @updated 11-Oct-2006 02:56:12 PM
 */
public interface IExpressionId extends IExpressionOperand
{

	public int getInt();

}
