/*L
 * Copyright Washington University in St. Louis, SemanticBits, Persistent Systems, Krishagni.
 *
 * Distributed under the OSI-approved BSD 3-Clause License.
 * See http://ncip.github.com/wustl-common-package/LICENSE.txt for details.
 */

package edu.wustl.common.querysuite.queryobject;

/**
 * An immutable wrapper around int used to uniquely identify an expression
 * within a query. It is autogenerated when an expression is added to a query.
 * @see edu.wustl.common.querysuite.queryobject.IConstraints#addExpression(IFunctionalClass)
 * @version 1.0
 * @updated 11-Oct-2006 02:56:12 PM
 */
public interface IExpressionId extends IExpressionOperand
{

	/**
	 * To get the integer value assigned to this Expression id.
	 * @return The integer value sassigned to this Expression id.
	 */
	int getInt();

}
